In [24]:
import pandas as pd
import numpy as np

metrics = ['GED (Fidelity)', 'Latent Euclidean Distance (Fidelity)', 'Latent Cossimilary (Fidelity)', 'Absolute Difference (Validity)', 'flip-ratio (Validity)']
methods = ['random_sampled_CFs_list (mean)', 'closest_graph_train (mean)', 'closest_latent_train (mean)', 'main_method (mean)']

methods_name_map = {
    'random_sampled_CFs_list (mean)': 'Random',
    'closest_latent_train (mean)': 'Decoded Mean of k-NN',
    'closest_graph_train (mean)': 'Graph of NN from Training',
    'main_method (mean)': 'Classifier Guided CF',
}

metric_name_map = {
    'GED (Fidelity)': 'GED (Fidelity) \\downarrow',
    'Latent Euclidean Distance (Fidelity)': 'Latent Euclidean Distance (Fidelity) \\downarrow',
    'Latent Cossimilary (Fidelity)': 'Latent Cossimilary (Fidelity) \\uparrow',
    'Absolute Difference (Validity)': 'Absolute Difference (Validity) \\uparrow',
    'flip-ratio (Validity)': 'flip-ratio (Validity) \\uparrow'
}

latex_config = {
    'column_format': 'c|ccc||cc',
    'float_format': "%.2f",
}

def configure_dataframes(path,):
    df = pd.read_csv(path, index_col=0)
    df_t = df[methods].rename(columns=methods_name_map).transpose()
    for metric in metrics:
        if not metric in df_t.keys():
            df_t[metric] = np.nan
    #filtered_metrics = filter(lambda x: x in df.transpose().keys(), metrics)
    return df_t[metrics].round(decimals=2).rename(columns=metric_name_map)

def format_mean_std(mean, std):
    if pd.isna(std):  # Check if std is NaN
        return f"{mean}"  # Only return the mean without ±
    else:
        return f"{mean} $\\pm$ {{\\small {std}}}"  # Return mean ± std

def get_result_dataframe(df_mean, df_std):
    results = pd.DataFrame(
        {col: [format_mean_std(m, s) for m, s in zip(df_mean[col], df_std[col])] for col in df_mean.columns},
        index=df_mean.index
    )
    latex_results = results.to_latex(**latex_config)
    return results, latex_results

## Aids

In [30]:
# Paths
method = 'test_aids'
path_mean = f'./data/predictions/{method}_method_statistics/aggregated_mean_counterfactual_statistics.csv'
path_std = f'./data/predictions/{method}_method_statistics/aggregated_std_counterfactual_statistics.csv'

results_aids, latex_results = get_result_dataframe(configure_dataframes(path_mean), configure_dataframes(path_std))
results_aids

,GED (Fidelity) \downarrow,Latent Euclidean Distance (Fidelity) \downarrow,Latent Cossimilary (Fidelity) \uparrow,Absolute Difference (Validity) \uparrow,flip-ratio (Validity) \uparrow
Random,63.4 $\pm$ {\small 19.63},14.95 $\pm$ {\small 2.62},-0.01 $\pm$ {\small 0.41},0.83 $\pm$ {\small 0.38},0.83
Graph of NN from Training,18.54 $\pm$ {\small 9.95},8.31 $\pm$ {\small 1.82},0.15 $\pm$ {\small 0.38},0.4 $\pm$ {\small 0.43},0.33
Decoded Mean of k-NN,47.66 $\pm$ {\small 10.84},8.44 $\pm$ {\small 1.95},-0.19 $\pm$ {\small 0.14},0.99 $\pm$ {\small 0.03},1.0
Classifier Guided CF,35.79 $\pm$ {\small 14.01},7.11 $\pm$ {\small 2.35},-0.08 $\pm$ {\small 0.25},0.94 $\pm$ {\small 0.15},0.98

In [26]:
print(latex_results)

\begin{tabular}{c|ccc||cc}
\toprule
 & GED (Fidelity) \downarrow & Latent Euclidean Distance (Fidelity) \downarrow & Latent Cossimilary (Fidelity) \uparrow & Absolute Difference (Validity) \uparrow & flip-ratio (Validity) \uparrow \\
\midrule
Random & 78.15 $\pm$ {\small 23.06} & 9.08 $\pm$ {\small 1.34} & -0.08 $\pm$ {\small 0.37} & 0.86 $\pm$ {\small 0.36} & 0.87 \\
Graph of NN from Training & 17.73 $\pm$ {\small 8.5} & 4.65 $\pm$ {\small 0.89} & 0.14 $\pm$ {\small 0.36} & 0.36 $\pm$ {\small 0.43} & 0.31 \\
Decoded Mean of k-NN & 50.75 $\pm$ {\small 12.98} & 4.52 $\pm$ {\small 0.96} & -0.23 $\pm$ {\small 0.17} & 0.97 $\pm$ {\small 0.14} & 0.98 \\
Classifier Guided CF & 39.66 $\pm$ {\small 17.28} & 4.34 $\pm$ {\small 1.26} & -0.16 $\pm$ {\small 0.23} & 0.93 $\pm$ {\small 0.18} & 0.98 \\
\bottomrule
\end{tabular}

In [27]:
#save_df_as_csv(df, f'./data/predictions/{file_prefix}latex_table')
with open(f'./data/predictions/latex_tables/{method}_latex_table.tex', 'w') as tf:
    tf.write(latex_results)

## Mutagenicity

In [32]:
method = 'test_mutagenicity'
path_mean = f'./data/predictions/{method}_method_statistics/aggregated_mean_counterfactual_statistics.csv'
path_std = f'./data/predictions/{method}_method_statistics/aggregated_std_counterfactual_statistics.csv'

results_mutagenicity, latex_results = get_result_dataframe(configure_dataframes(path_mean), configure_dataframes(path_std))
results_mutagenicity

,GED (Fidelity) \downarrow,Latent Euclidean Distance (Fidelity) \downarrow,Latent Cossimilary (Fidelity) \uparrow,Absolute Difference (Validity) \uparrow,flip-ratio (Validity) \uparrow
Random,65.28 $\pm$ {\small 19.84},8.53 $\pm$ {\small 0.84},0.03 $\pm$ {\small 0.32},0.16 $\pm$ {\small 0.37},0.52
Graph of NN from Training,28.1 $\pm$ {\small 17.87},1.24 $\pm$ {\small 0.45},0.59 $\pm$ {\small 0.34},0.14 $\pm$ {\small 0.25},0.44
Decoded Mean of k-NN,41.24 $\pm$ {\small 18.93},1.05 $\pm$ {\small 0.36},0.42 $\pm$ {\small 0.39},0.09 $\pm$ {\small 0.3},0.41
Classifier Guided CF,50.62 $\pm$ {\small 21.41},3.63 $\pm$ {\small 2.09},0.1 $\pm$ {\small 0.46},0.42 $\pm$ {\small 0.33},0.92

In [33]:
print(latex_results)

\begin{tabular}{c|ccc||cc}
\toprule
 & GED (Fidelity) \downarrow & Latent Euclidean Distance (Fidelity) \downarrow & Latent Cossimilary (Fidelity) \uparrow & Absolute Difference (Validity) \uparrow & flip-ratio (Validity) \uparrow \\
\midrule
Random & 65.28 $\pm$ {\small 19.84} & 8.53 $\pm$ {\small 0.84} & 0.03 $\pm$ {\small 0.32} & 0.16 $\pm$ {\small 0.37} & 0.52 \\
Graph of NN from Training & 28.1 $\pm$ {\small 17.87} & 1.24 $\pm$ {\small 0.45} & 0.59 $\pm$ {\small 0.34} & 0.14 $\pm$ {\small 0.25} & 0.44 \\
Decoded Mean of k-NN & 41.24 $\pm$ {\small 18.93} & 1.05 $\pm$ {\small 0.36} & 0.42 $\pm$ {\small 0.39} & 0.09 $\pm$ {\small 0.3} & 0.41 \\
Classifier Guided CF & 50.62 $\pm$ {\small 21.41} & 3.63 $\pm$ {\small 2.09} & 0.1 $\pm$ {\small 0.46} & 0.42 $\pm$ {\small 0.33} & 0.92 \\
\bottomrule
\end{tabular}

In [34]:
#save_df_as_csv(df, f'./data/predictions/{file_prefix}latex_table')
with open(f'./data/predictions/latex_tables/{method}_latex_table.tex', 'w') as tf:
    tf.write(latex_results)

## NCI1

In [42]:
method = 'test_nci1'
path_mean = f'./data/predictions/{method}_method_statistics/aggregated_mean_counterfactual_statistics.csv'
path_std = f'./data/predictions/{method}_method_statistics/aggregated_std_counterfactual_statistics.csv'

results_nci1, latex_results = get_result_dataframe(configure_dataframes(path_mean), configure_dataframes(path_std))
results_nci1

,GED (Fidelity) \downarrow,Latent Euclidean Distance (Fidelity) \downarrow,Latent Cossimilary (Fidelity) \uparrow,Absolute Difference (Validity) \uparrow,flip-ratio (Validity) \uparrow
Random,59.94 $\pm$ {\small 17.01},41.04 $\pm$ {\small 3.18},-0.01 $\pm$ {\small 0.21},0.11 $\pm$ {\small 0.43},0.49
Graph of NN from Training,40.51 $\pm$ {\small 16.44},8.67 $\pm$ {\small 3.29},0.58 $\pm$ {\small 0.35},0.15 $\pm$ {\small 0.25},0.58
Decoded Mean of k-NN,42.59 $\pm$ {\small 15.82},8.0 $\pm$ {\small 3.04},0.38 $\pm$ {\small 0.3},0.13 $\pm$ {\small 0.34},0.51
Classifier Guided CF,53.14 $\pm$ {\small 23.01},13.19 $\pm$ {\small 12.1},0.3 $\pm$ {\small 0.44},0.34 $\pm$ {\small 0.25},1.0

In [43]:
print(latex_results)

\begin{tabular}{c|ccc||cc}
\toprule
 & GED (Fidelity) \downarrow & Latent Euclidean Distance (Fidelity) \downarrow & Latent Cossimilary (Fidelity) \uparrow & Absolute Difference (Validity) \uparrow & flip-ratio (Validity) \uparrow \\
\midrule
Random & 59.94 $\pm$ {\small 17.01} & 41.04 $\pm$ {\small 3.18} & -0.01 $\pm$ {\small 0.21} & 0.11 $\pm$ {\small 0.43} & 0.49 \\
Graph of NN from Training & 40.51 $\pm$ {\small 16.44} & 8.67 $\pm$ {\small 3.29} & 0.58 $\pm$ {\small 0.35} & 0.15 $\pm$ {\small 0.25} & 0.58 \\
Decoded Mean of k-NN & 42.59 $\pm$ {\small 15.82} & 8.0 $\pm$ {\small 3.04} & 0.38 $\pm$ {\small 0.3} & 0.13 $\pm$ {\small 0.34} & 0.51 \\
Classifier Guided CF & 53.14 $\pm$ {\small 23.01} & 13.19 $\pm$ {\small 12.1} & 0.3 $\pm$ {\small 0.44} & 0.34 $\pm$ {\small 0.25} & 1.0 \\
\bottomrule
\end{tabular}

In [44]:
#save_df_as_csv(df, f'./data/predictions/{file_prefix}latex_table')
with open(f'./data/predictions/latex_tables/{method}_latex_table.tex', 'w') as tf:
    tf.write(latex_results)

## All Tables

In [45]:
all_results = pd.concat([results_aids, results_mutagenicity, results_nci1], keys=['Aids', 'Mutagenicity', 'NCI1'])
latex_results = all_results.to_latex(**latex_config)
all_results

                                         GED (Fidelity) \downarrow  \
Aids         Random                      63.4 $\pm$ {\small 19.63}
             Graph of NN from Training   18.54 $\pm$ {\small 9.95}
             Decoded Mean of k-NN       47.66 $\pm$ {\small 10.84}
             Classifier Guided CF       35.79 $\pm$ {\small 14.01}
Mutagenicity Random                     65.28 $\pm$ {\small 19.84}
             Graph of NN from Training   28.1 $\pm$ {\small 17.87}
             Decoded Mean of k-NN       41.24 $\pm$ {\small 18.93}
             Classifier Guided CF       50.62 $\pm$ {\small 21.41}
NCI1         Random                     59.94 $\pm$ {\small 17.01}
             Graph of NN from Training  40.51 $\pm$ {\small 16.44}
             Decoded Mean of k-NN       42.59 $\pm$ {\small 15.82}
             Classifier Guided CF       53.14 $\pm$ {\small 23.01}

                                       Latent Euclidean Distance (Fidelity) \downarrow  \
Aids         Random                                          14.95 $\pm$ {\small 2.62}
             Graph of NN from Training                        8.31 $\pm$ {\small 1.82}
             Decoded Mean of k-NN                             8.44 $\pm$ {\small 1.95}
             Classifier Guided CF                             7.11 $\pm$ {\small 2.35}
Mutagenicity Random                                           8.53 $\pm$ {\small 0.84}
             Graph of NN from Training                        1.24 $\pm$ {\small 0.45}
             Decoded Mean of k-NN                             1.05 $\pm$ {\small 0.36}
             Classifier Guided CF                             3.63 $\pm$ {\small 2.09}
NCI1         Random                                          41.04 $\pm$ {\small 3.18}
             Graph of NN from Training                        8.67 $\pm$ {\small 3.29}
             Decoded Mean of k-NN                              8.0 $\pm$ {\small 3.04}
             Classifier Guided CF                            13.19 $\pm$ {\small 12.1}

                                       Latent Cossimilary (Fidelity) \uparrow  \
Aids         Random                                 -0.01 $\pm$ {\small 0.41}
             Graph of NN from Training               0.15 $\pm$ {\small 0.38}
             Decoded Mean of k-NN                   -0.19 $\pm$ {\small 0.14}
             Classifier Guided CF                   -0.08 $\pm$ {\small 0.25}
Mutagenicity Random                                  0.03 $\pm$ {\small 0.32}
             Graph of NN from Training               0.59 $\pm$ {\small 0.34}
             Decoded Mean of k-NN                    0.42 $\pm$ {\small 0.39}
             Classifier Guided CF                     0.1 $\pm$ {\small 0.46}
NCI1         Random                                 -0.01 $\pm$ {\small 0.21}
             Graph of NN from Training               0.58 $\pm$ {\small 0.35}
             Decoded Mean of k-NN                     0.38 $\pm$ {\small 0.3}
             Classifier Guided CF                     0.3 $\pm$ {\small 0.44}

                                       Absolute Difference (Validity) \uparrow  \
Aids         Random                                   0.83 $\pm$ {\small 0.38}
             Graph of NN from Training                 0.4 $\pm$ {\small 0.43}
             Decoded Mean of k-NN                     0.99 $\pm$ {\small 0.03}
             Classifier Guided CF                     0.94 $\pm$ {\small 0.15}
Mutagenicity Random                                   0.16 $\pm$ {\small 0.37}
             Graph of NN from Training                0.14 $\pm$ {\small 0.25}
             Decoded Mean of k-NN                      0.09 $\pm$ {\small 0.3}
             Classifier Guided CF                     0.42 $\pm$ {\small 0.33}
NCI1         Random                                   0.11 $\pm$ {\small 0.43}
             Graph of NN from Training                0.15 $\pm$ {\small 0.25}
             Decoded Mean of k-NN                     0.13 $\pm$ {\small 0.34}
             Classifier Guided CF                     0.34 $\pm$ {\small 0.25}

                                       flip-ratio (Validity) \uparrow
Aids         Random                                              0.83
             Graph of NN from Training                           0.33
             Decoded Mean of k-NN                                 1.0
             Classifier Guided CF                                0.98
Mutagenicity Random                                              0.52
             Graph of NN from Training                           0.44
             Decoded Mean of k-NN                                0.41
             Classifier Guided CF                                0.92
NCI1         Random                                              0.49
             Graph of NN from Training                           0.58
             Decoded Mean of k-NN                                0.51
             Classifier Guided CF                                 1.0

In [46]:
print(all_results)

                                         GED (Fidelity) \downarrow  \
Aids         Random                      63.4 $\pm$ {\small 19.63}
             Graph of NN from Training   18.54 $\pm$ {\small 9.95}
             Decoded Mean of k-NN       47.66 $\pm$ {\small 10.84}
             Classifier Guided CF       35.79 $\pm$ {\small 14.01}
Mutagenicity Random                     65.28 $\pm$ {\small 19.84}
             Graph of NN from Training   28.1 $\pm$ {\small 17.87}
             Decoded Mean of k-NN       41.24 $\pm$ {\small 18.93}
             Classifier Guided CF       50.62 $\pm$ {\small 21.41}
NCI1         Random                     59.94 $\pm$ {\small 17.01}
             Graph of NN from Training  40.51 $\pm$ {\small 16.44}
             Decoded Mean of k-NN       42.59 $\pm$ {\small 15.82}
             Classifier Guided CF       53.14 $\pm$ {\small 23.01}

                                       Latent Euclidean Distance (Fidelity) \downarrow  \
Aids         Random                                          14.95 $\pm$ {\small 2.62}
             Graph of NN from Training                        8.31 $\pm$ {\small 1.82}
             Decoded Mean of k-NN                             8.44 $\pm$ {\small 1.95}
             Classifier Guided CF                             7.11 $\pm$ {\small 2.35}
Mutagenicity Random                                           8.53 $\pm$ {\small 0.84}
             Graph of NN from Training                        1.24 $\pm$ {\small 0.45}
             Decoded Mean of k-NN                             1.05 $\pm$ {\small 0.36}
             Classifier Guided CF                             3.63 $\pm$ {\small 2.09}
NCI1         Random                                          41.04 $\pm$ {\small 3.18}
             Graph of NN from Training                        8.67 $\pm$ {\small 3.29}
             Decoded Mean of k-NN                              8.0 $\pm$ {\small 3.04}
             Classifier Guided CF                            13.19 $\pm$ {\small 12.1}

                                       Latent Cossimilary (Fidelity) \uparrow  \
Aids         Random                                 -0.01 $\pm$ {\small 0.41}
             Graph of NN from Training               0.15 $\pm$ {\small 0.38}
             Decoded Mean of k-NN                   -0.19 $\pm$ {\small 0.14}
             Classifier Guided CF                   -0.08 $\pm$ {\small 0.25}
Mutagenicity Random                                  0.03 $\pm$ {\small 0.32}
             Graph of NN from Training               0.59 $\pm$ {\small 0.34}
             Decoded Mean of k-NN                    0.42 $\pm$ {\small 0.39}
             Classifier Guided CF                     0.1 $\pm$ {\small 0.46}
NCI1         Random                                 -0.01 $\pm$ {\small 0.21}
             Graph of NN from Training               0.58 $\pm$ {\small 0.35}
             Decoded Mean of k-NN                     0.38 $\pm$ {\small 0.3}
             Classifier Guided CF                     0.3 $\pm$ {\small 0.44}

                                       Absolute Difference (Validity) \uparrow  \
Aids         Random                                   0.83 $\pm$ {\small 0.38}
             Graph of NN from Training                 0.4 $\pm$ {\small 0.43}
             Decoded Mean of k-NN                     0.99 $\pm$ {\small 0.03}
             Classifier Guided CF                     0.94 $\pm$ {\small 0.15}
Mutagenicity Random                                   0.16 $\pm$ {\small 0.37}
             Graph of NN from Training                0.14 $\pm$ {\small 0.25}
             Decoded Mean of k-NN                      0.09 $\pm$ {\small 0.3}
             Classifier Guided CF                     0.42 $\pm$ {\small 0.33}
NCI1         Random                                   0.11 $\pm$ {\small 0.43}
             Graph of NN from Training                0.15 $\pm$ {\small 0.25}
             Decoded Mean of k-NN                     0.13 $\pm$ {\small 0.34}
             Classifier Guided CF                     0.34 $\pm$ {\small 0.25}

                                       flip-ratio (Validity) \uparrow
Aids         Random                                              0.83
             Graph of NN from Training                           0.33
             Decoded Mean of k-NN                                 1.0
             Classifier Guided CF                                0.98
Mutagenicity Random                                              0.52
             Graph of NN from Training                           0.44
             Decoded Mean of k-NN                                0.41
             Classifier Guided CF                                0.92
NCI1         Random                                              0.49
             Graph of NN from Training                           0.58
             Decoded Mean of k-NN                                0.51
             Classifier Guided CF                                 1.0

In [47]:
#save_df_as_csv(df, f'./data/predictions/{file_prefix}latex_table')
prefix = method.split('_')[0]
with open(f'./data/predictions/latex_tables/{prefix}_all_latex_table.tex', 'w') as tf:
    tf.write(latex_results)